Fix broken packaging
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%WWWDIR%%/classes/cache-category.php
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/dvl/freshports-www



git-svn-id: svn://127.0.0.16/websites/ports@8796 e9903129-21d8-e211-989e-002590a4cdd4